Revert "sdm710-common: Build thermal HIDL HAL"
ERROR: files are incompatible: android.hardware.thermal@1.0::IThermal/default is deprecated in compatibility matrix at FCM Version 4; it should not be served.
android.hardware.thermal@1.0::IThermal/default is deprecated in compatibility matrix at FCM Version 4; it should not be served.: Success

This reverts commit de21c8d196d052cf7339689c786d6d4aad2ed8a4.